### PR TITLE
fixes a bug while parsing regression datasets

### PR DESCRIPTION
**Pull request by joaquinvanschoren**
Fixes https://github.com/openml/EvaluationEngine/issues/29

### CODE REVIEW

**Comment by janvanrijn** [comment]
Can you please submit to development branch? 

Also, something seems to go wrong. I think the idea is as follows:
- num classes is 0 in case of no class set
- num classes is 1 in case of regression
- num classes is higher in case of classification?

Otherwise, 
- num classes is 0 in case of no class set or regression
- num classes is higher in case of classification?

I am a bit torn between these two options.

**Comment by joaquinvanschoren** [comment]
Sorry, GH automatically chose master. Now switched to develop.

The problem here was that we use WEKA's Instances.numClasses() here: https://github.com/openml/EvaluationEngine/commit/7be41b09992e570d7159e61ba95e6bcdaee42f2c

That returns 1 in case of a numeric target attribute, so it seems that you already working with the first option? 
For AttributeStatistics, this is only used to check whether we want to compute the per-class statistics. Either way this only makes sense if there are at least two classes and the target attribute is set.

**Comment by joaquinvanschoren** [comment]
Hi @janvanrijn. Can we merge or do we need to discuss this further?

**Comment by janvanrijn** [comment]
continued in #31

**Pull request closed without merging**
